config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'locations#index'
  resources :locations
  resources :locations do
    resources :comments do
      member do
        get :cancel_edit, as: :cancel_edit
      end
    end
  end
  post 'asset_uploads', to: 'asset_uploads#create'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :location
  has_rich_text :content

  validates :content, presence: true

  paginates_per 4
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates_presence_of :name, :latitude, :longitude
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments, reject_if: :reject_blank_comment, allow_destroy: true

  before_validation :process_ratings

  paginates_per 10

  def self.update_categories
    const_set(:CATEGORIES, Category.pluck(:name).freeze)
  end

  update_categories

  private

  def process_ratings
    ratings_data = ratings.reject { |_, value| value.blank? }
    self.ratings = {} if ratings_data.blank?

    return if ratings_data.blank?

    transformed_hash = ratings_data.transform_values(&:to_i)
    CATEGORIES.each do |category|
      rating = transformed_hash[category]
      transformed_hash[category] = rating if rating.present?
    end

    self.ratings = transformed_hash
  end

  def reject_blank_comment(attributes)
    attributes['content'].blank?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/asset_uploads_controller.rb
# frozen_string_literal: true

# app/controllers/image_uploads_controller.rb
class AssetUploadsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    if asset_missing?
      return render json: { error: 'Oops! File must exist' },
                    status: :unprocessable_entity
    end

    result = Cloudinary::CloudinaryUploadService.call(
      file: params[:file],
      folder: 'come_across_uploads'
    )
    if result.success
      render json: { url: result.secure_url }, status: :ok
    else
      render json: { error: result.error_message },
             status: :unprocessable_entity
    end
  end

  def asset_missing?
    params[:file].nil? || params[:file].blank?
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_location, only: %i[create show edit update destroy cancel_edit]
  before_action :set_comment, only: %i[show edit update destroy]

  def create
    @comment = @location.comments.build(comment_params)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to @location, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @location }
      end
    else
      respond_to do |format|
        errors_message = @comment.errors.full_messages.join(', ')
        format.html { redirect_to @location, notice: errors_message }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.json { render json: @comment }
    end
  end

  def edit; end

  def cancel_edit
    respond_to do |format|
      format.html { redirect_to @location, notice: 'Changes were not saved.' }
      format.json do
        render json: { message: 'Changes were not saved.' }, status: :unprocessable_entity
      end
    end
  end

  def update
    if @comment.update(comment_params)
      respond_to do |format|
        format.html { redirect_to @location, notice: 'Comment was successfully updated.' }
        format.json { render json: @comment, status: :ok, location: @location }
      end
    else
      respond_to do |format|
        format.html do
          redirect_to @location, alert: @comment.errors.full_messages.join(', ')
        end
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @location, notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_location
    @location = Location.find(params[:location_id])
  end

  def set_comment
    location = Location.find(params[:location_id])
    @comment = location.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:location_id, :content)
  end
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  before_action :set_location, only: %i[show edit update destroy]

  def index
    @locations = Location.includes(comments: :rich_text_content)
                         .page(params[:page])
                         .order(updated_at: :desc)

    respond_to do |format|
      format.html
      format.json { render json: @locations }
    end
  end

  # GET /locations/1 or /locations/1.json
  def show
    @comments = @location.comments
                         .page(params[:page])
                         .order(created_at: :desc)
    respond_to do |format|
      format.html
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
    @location.comments.build

    respond_to do |format|
      format.html
      format.json { render json: @location }
    end
  end

  def edit
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @location }
    end
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)
    respond_to do |format|
      if @location.save
        format.html do
          redirect_to location_url(@location),
                      flash: { notice: 'Location was successfully created.' }
        end
        format.json { render :show, status: :created, location: @location }
      else
        errors_message = @location.errors.full_messages.join(', ')
        format.html do
          redirect_to new_location_url,
                      alert: errors_message
        end

        format.json do
          render json: @location.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html do
          redirect_to location_url(@location),
                      notice: 'Location was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @location }
      else
        errors_message = @location.errors.full_messages.join(', ')
        format.html do
          redirect_to edit_location_url, alert: errors_message
        end
        format.json do
          render json: @location.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy

    respond_to do |format|
      format.html do
        redirect_to locations_url,
                    notice: 'Location was successfully deleted.'
      end
      format.json { head :no_content }
    end
  end

  private

  def set_location
    @location = Location.includes(comments: :rich_text_content).find(params[:id])
  end

  def location_params
    params.require(:location).permit(
      :name,
      :latitude,
      :longitude,
      :dates,
      :address,
      ratings: Location::CATEGORIES,
      comments_attributes: %i[content]
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def render_stars(rating)
    output = ''
    if (1..5).include?(rating.to_i)
      full_stars = rating.to_i
      empty_stars = 5 - full_stars

      output += '<span class="stars">'
      full_stars.times { output += '<i class="star filled"></i>' }
      empty_stars.times { output += '<i class="star empty"></i>' }
      output += '</span>'
    end
    output.html_safe
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 500, 300 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_edit_comment_form.html.erb
<!-- views/comments/_edit_comment_form.html.erb -->
<%= form_with(model: comment, url: location_comment_path(location, comment), method: :patch, remote: true) do |form| %>
  <%= form.rich_text_area :content, class: 'custom-image', data: { direct_upload_url: asset_uploads_path } %>
  <div class="text-end"> 
    <%= form.submit "Update Comment", class: "btn btn-primary btn-sm mt-2" %>
    <%= link_to "Cancel", cancel_edit_location_comment_path(location), method: :get, class: "btn btn-secondary btn-sm mt-2" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<!-- views/comments/edit.html.erb -->
<div class="container d-flex align-items-center justify-content-center">
  <div class="">
    <%= render partial: 'comments/edit_comment_form', locals: { comment: @comment, location: @location } %>
</div>
</div>

app/views/layouts/_alerts.html.erb
<div class="container d-flex align-items-center justify-content-center">
  <div class="container-md">
    <% if notice.present? %>
      <div style="color: green" class="alert alert-primary" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div style="color: red" class="alert alert-primary" role="alert">
        <%= alert %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light  bg-primary" >
  <div class="container-fluid" >
    <%= link_to "Come Across", root_path, class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
    data-bs-target="#navbarSupportedContent" 
    aria-controls="navbarSupportedContent" 
    aria-expanded="false" aria-label="Toggle navigation">
      <span  class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Come Across</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag 'rating_validation' %>
  <%= javascript_include_tag 'asset_uploader' %>
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.0/dist/trix.css">
  <script type="text/javascript" src="https://unpkg.com/trix@2.0.0/dist/trix.umd.min.js"></script>
</head>
<body>
  <header>
    <%= render 'layouts/navbar' %>
    <br/>
    <%= render 'layouts/alerts' %>
  </header>
  <main>
    <%= yield %>
  </main>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location) do |form| %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="form-group"> 
    <%= form.label :name, style: "display: block; margin-top: 1rem;" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :latitude, style: "display: block; margin-top: 1rem;" %>
    <%= form.text_field :latitude, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :longitude, style: "display: block; margin-top: 1rem;" %>
    <%= form.text_field :longitude, class: 'form-control' %>
  </div>

  <div class="form-group">
   <%= form.label :address, style: "display: block; margin-top: 1rem;" %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>
  <br/>

  <p class="lead">Ratings:</p>
  <div>
    <% Location::CATEGORIES.each do |category| %>
      <div class="form-group">
        <%= form.label "ratings[#{category}]", category %>
        <%= form.number_field "ratings[#{category}]",
                              min: 1,
                              max: 5,
                              class: 'form-control rating-input',
                              step: 1,
                              value: location.ratings[category] %>
      </div>
    <% end %>
  </div>

  <br/>
  <p class="lead">Date:</p>
  <div>
    <%= form.text_field :dates, class: 'form-control custom-date-field', type: 'date' %>
  </div>

  <% if action_name == 'new' %>
    <br/>
    <p class="lead">Comments:</p>
    <div>
      <%= form.fields_for :comments do |comment_form| %>
        <div class="field">
          <%= hidden_field_tag :attachment_urls, nil, id: "attachment-urls" %>
        </div>
        <%= comment_form.rich_text_area :content,
                                        class: 'custom-image',
                                        data: { direct_upload_url: asset_uploads_path } %>
      <% end %>
    </div>
  <% end %>

  <div class="d-flex justify-content-between mt-4">
    <div class="actions">
      <%= link_to "Cancel", locations_path, class: "btn btn-secondary w-100" %>
    </div>
    <div class="actions me-4">
      <% if location.new_record? %>
        <%= form.button "Create Location", type: :submit, class: "btn btn-primary" %>
      <% else %>
        <%= form.button "Update Location", type: :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div class="card" style="width: 100%;">
  <div class="card-body">
    <h5 class="card-title">
      <h2><%= location.name %></h2>
    </h5>

    <% if location.address? %>
      <p class="lead">
        Address:
        <%= location.address %>
      </p>
    <% end %>

    <p class="lead">
      Latitude:
      <%= location.latitude %>
    </p>

    <p class="lead">
      Longitude:
      <%= location.longitude %>
    </p>
    <% if location.dates? %>
    <p class="lead">
      Visited:
      <%= "#{time_ago_in_words(location.dates)} ago" %>
    </p>
    <% end %>

    <% if location.ratings? %>
      <h4>Ratings</h4>
      <% location.ratings.each do |category, rating| %>
        <p class="lead"><%= category %>: <p><%= render_stars(rating) %></p></p>
      <% end %>
    <% end %>
    
    <div class="text-end">
      <%= link_to "View Location Details", location_path(location), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/locations/_location_comments.html.erb
  <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button <%= 'collapsed' if @comments&.blank? %>" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="<%= !@comments&.blank? %>" aria-controls="collapseOne">
          <h2 class="comments-heading">Comments</h2>
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse <%= 'show' unless @comments&.blank? %>" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <% if @comments&.size > 0 %>
            <div class="comments-section">
              <div class="comments-content">
                <% @comments&.each do |comment| %>
                  <div style="display: flex; flex-direction: column;">
                    <div style="padding: 0.5rem; background-color: #f0f0f0; border-radius: 0.25rem; margin-top: 0.75rem;">
                      <small> <%= comment.content %> </small>
                      <br/>
                      <small>Posted: <%= "#{time_ago_in_words(comment.created_at)} ago" %> </small>
                      <br/>
                      <br/>
                      <!-- Update/Delete comment section -->
                      <div class="d-flex justify-content-between">
                        
                        <%= form_with(model: comment, url: location_comment_path(location, comment), method: :delete) do |form| %>
                          <%= form.hidden_field :_method, value: :delete %>
                          <%= form.submit "Delete Comment", data: { confirm: "Are you sure you want to delete this comment?" }, class: "btn btn-danger btn-sm mt-2" %>
                        <% end %>
                        <%= button_to "Update Comment", edit_location_comment_path(location, comment), method: :get, class: "btn btn-primary btn-sm mt-2", remote: true %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>

          <!-- Comments pagination -->
          <div class="d-flex justify-content-between mt-4">
            <% if @comments&.prev_page %>
              <a href="<%= url_for(page: @comments.prev_page) %>" style="text-decoration: none;">
                <span style="font-size: 1.5rem;" aria-hidden="true">&laquo;</span>
              </a>
            <% else %>
              <span style="font-size: 1.5rem; color: #6c757d;" aria-hidden="true">&laquo;</span>
            <% end %>

            <% if @comments&.next_page %>
              <a href="<%= url_for(page: @comments&.next_page) %>" style="text-decoration: none;">
                <span style="font-size: 1.5rem;" aria-hidden="true">&raquo;</span>
              </a>
            <% else %>
              <span style="font-size: 1.5rem; color: #6c757d;" aria-hidden="true">&raquo;</span>
            <% end %>
          </div>
        
        </div>
      </div>
    </div>

    <br/>
    <!-- Form to create new comments -->
    <%= form_with(model: [location, Comment.new], url: location_comments_path(location)) do |form| %>
      <%= form.hidden_field :location_id, value: location.id %>
      <%= form.rich_text_area :content, class: 'custom-image', data: { direct_upload_url: asset_uploads_path } %>
      <div class="text-end"> 
        <%= form.submit "Add comment", class: "btn btn-primary btn-sm mt-2 mb-2" %>
      </div>
    <% end %>

  </div>

app/views/locations/_location_details.html.erb
<div id="<%= dom_id(location) %>">
  <h5 class="card-title">
    <h2><%= location.name %></h2>
  </h5>

  <% if location.address? %>
    <p class="lead">
      Address:
      <%= location.address %>
    </p>
  <% end %>

  <p class="lead">
    Latitude:
    <%= location.latitude %>
  </p>

  <p class="lead">
    Longitude:
    <%= location.longitude %>
  </p>

  <% if location.dates? %>
    <p class="lead">
      Visited:
      <%= "#{time_ago_in_words(location.dates)} ago" %>
    </p>
  <% end %>

  <% if location.ratings? %>
    <h4>Ratings</h4>
    <% location.ratings.each do |category, rating| %>
      <p class="lead"><%= category %>: <p><%= render_stars(rating) %></p></p>
    <% end %>
  <% end %>

  <% marker_data = [{
    latitude: location.latitude,
    longitude: location.longitude,
    tooltip: location.address,
    label: location.name
  }]
  %>
  
  <!-- Display the map using the js_map helper with specific marker data -->
  <%= js_map marker_data, style: "mapbox://styles/mapbox/outdoors-v12", tooltips: { html: true, hover: true } %>

  <br/>
  <!-- Display the comments using rich_text_area content in a location comments partial -->
  <%= render "locations/location_comments", location: location, comments: @comments %>
</div>

app/views/locations/edit.html.erb
<div class="container d-flex align-items-center justify-content-center">
  <div class="container-md" style="min-width: 50vw;">
    <div>
      <h1>Edit location</h1>
      <%= render "form", location: @location %>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<div class="container d-flex align-items-center justify-content-center">
 <div class="container-md" style="min-width: 50vw;">
    <div class="shadow-lg p-2 mb-2 bg-body-tertiary rounded">
      <div class="d-flex justify-content-between mt-2 mb-2">
        <h1 class="card-title">Locations</h1>
          <%= link_to "Add New Location", new_location_path, class: "btn btn-primary ms-4 d-inline-flex align-items-center", style: "height: 3rem;" %>
      </div>
    </div>

    <% if @locations.blank? %>
      <br/>
      <div class="container d-flex align-items-center justify-content-center">
        <div class="alert alert-primary" role="alert">
          Sorry, not sure if this is what you expected, locations have not been added yet!
        </div>
      </div>
    <% end %>

    <% if @locations.present? %>
      <div class="card">
        <div class="card-body">
          <div id="locations">
            <% @locations.each do |location| %>
              <%= render location %>
              <p><br>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="d-flex justify-content-between mt-2">
      <% if @locations.prev_page %>
        <%= link_to_prev_page @locations, 'Previous', class: "btn btn-primary", style: "min-width: 100px;" %>
      <% else %>
        <a href="#" class="btn btn-primary disabled" tabindex="-1" aria-disabled="true" style="min-width: 100px;">Previous</a>
      <% end %>

      <% if @locations.next_page %>
        <%= link_to_next_page @locations, 'Next', class: "btn btn-primary", style: "min-width: 100px;" %>
      <% else %>
        <a href="#" class="btn btn-primary disabled" tabindex="-1" aria-disabled="true" style="min-width: 100px;">Next</a>
      <% end %>
    </div>

  </div>
</div>

app/views/locations/new.html.erb
<div class="container d-flex align-items-center justify-content-center">
  <div class="">  
  <h1>Add New location</h1>
    <%= render "form", location: @location %>
  </div>
</div>

app/views/locations/show.html.erb
<div class="container-md" style="min-width: 50vw;">
  <div class="card">
    <div class="card-body">
      <%= render partial: 'locations/location_details', locals: { location: @location, comments: @comments } %>
      <div class="d-flex justify-content-between mt-4">
        <div class="me-auto"> 
          <%= link_to "Delete Location", @location, method: :delete,
                                                class: "btn btn-danger btn-sm" ,
                                                data: { confirm: "Are you sure you want to delete this location?" } %>
        </div>
        <div class="mx-auto">
          <%= link_to "Update Location", edit_location_path(@location), class: "btn btn-primary btn-sm" %>
        </div>
        <div class="ms-auto">
          <%= link_to "Back", locations_path, class: "btn btn-primary btn-sm" %>
        </div>
      </div>
    </div>
  </div>
</div>